### ISSUE TITLE
FIXME

### ISSUE THREAD

**Issue by jokereven** [FlareZone/flare-dapp.io#39]
- error node_modules/.pnpm/@clerk+nextjs@4.23.3_next@13.4.19_react-dom@18.2.0_react@18.2.0/node_modules/@clerk/nextjs/dist/esm/server/getAuth.js (28:12) @ eval
- error Error: Clerk: auth() was called but it looks like you aren't using `authMiddleware` in your middleware file. Please use `authMiddleware` and make sure your middleware matcher is configured correctly and it matches this route or page. See https://clerk.com/docs/quickstarts/get-started-with-nextjs
    at Header (./components/layouts/AppLayout/Header.tsx:14:75)
    at stringify (<anonymous>)
null
- error node_modules/.pnpm/@clerk+nextjs@4.23.3_next@13.4.19_react-dom@18.2.0_react@18.2.0/node_modules/@clerk/nextjs/dist/esm/server/getAuth.js (28:12) @ eval
- error Error: Clerk: auth() was called but it looks like you aren't using `authMiddleware` in your middleware file. Please use `authMiddleware` and make sure your middleware matcher is configured correctly and it matches this route or page. See https://clerk.com/docs/quickstarts/get-started-with-nextjs
    at Header (./components/layouts/AppLayout/Header.tsx:14:75)
    at stringify (<anonymous>)
digest: "1613934651"
null

**Comment by jokereven** [comment]
![image](https://github.com/FlareZone/flare-dapp.io/assets/73232691/da48a081-ff61-4984-b9ef-e7a4c133aa61)
so dope!
